<?php
//  php bin/console doctrine:fixtures:load  
namespace App\DataFixtures;

use App\Entity\Race;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use App\Entity\Type;

class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $types = ['Chien','Chat'];

        foreach ($types as $typeName) {
            $type = new Type();
            $type->setTypeAnimal($typeName);
            $manager->persist($type);
        }

        $manager->flush();

        $data = [ 
'Ainou;1',
'Airedale Terrier;1',
'Akbash;1',
'Akita Inu;1',
'Akita americain;1',
'Alangu Mastiff;1',
'Alano espagnol;1',
'Bulldog de sang bleu alpha;1',
'Alaskan Klee Kai;1',
'Alaunt;1',
'Alopekis;1',
'Intimidateur americain;1',
'Terrier glabre americain;1',
'Ariegeois ;1',
'Armant dog;1',
'Bandog;1',
'Bangkaew de Thailande ;1',
'Barbet ;1',
'Basenji ;1',
'Basset ardennais, race disparu;1',
'Basset artesien normand ;1',
'Basset d Artois;1',
'Basset bleu de Gascogne ;1',
'Basset des Alpes ;1',
'Basset fauve de Bretagne ;1',
'Basset hound ;1',
'Basset suedois;1',
'Basset de Westphalie;1',
'Beagle ;1',
'Beagle-harrier ;1',
'Beaglier;1',
'Bedlington Terrier ;1',
'Berger allemand ;1',
'Berger americain miniature ;1',
'Berger d Anatolie;1',
'Berger anglais ancestral;1',
'Berger d Artois race disparue;1',
'Berger d Asie centrale ;1',
'Berger australien ;1',
'Berger australien miniature;1',
'Berger d Auvergne;1',
'Berger basque;1',
'Berger de Beauce ;1',
'Berger belge ;1',
'Berger belge Groenendael ;1',
'Berger belge Laekenois ;1',
'Berger belge malinois ;1',
'Berger Belge Tervueren ;1',
'Berger de Bergame;1',
'Berger blanc suisse ;1',
'Berger de Boheme ;1',
'Berger de Bosnie-Herzegovine e;1',
'Berger de Brie;1',
'Berger bulgare;1',
'Berger catalan;1',
'Berger du Caucase;1',
'Berger de la Crau;1',
'Berger Croate ;1',
'Berger finnois de Laponie ;1',
'Berger Hellenique;1',
'Berger Himalayen;1',
'Berger hollandais ;1',
'Berger islandais ;1',
'Berger du Karst ;1',
'Berger du Larzac race disparue;1',
'Berger de Majorque ;1',
'Berger de Maremme et Abruzzes ;1',
'Berger picard ;1',
'Berger polonais de plaine ;1',
'Berger Portugais;1',
'Berger des Pyrenees;1',
'Berger des Pyrenees ? face ras;1',
'Berger des Pyrenees ? poil lon;1',
'Berger roumain;1',
'Berger roumain des Carpates ;1',
'Berger roumain de Mioritza ;1',
'Berger roumain Bucovina ;1',
'Berger de Russie meridionale o;1',
'Berger de Savoie ou berger des;1',
'Berger de Shiloh ;1',
'Berger des Shetland;1',
'Berger Tahitien;1',
'Berger des Tatras;1',
'Berger yougoslave de Charplani;1',
'Bouvier des Ardennes;1',
'Bouvier des Flandres;1',
'Boxer;1',
'Boykin Spaniel ;1',
'Brachet allemand ;1',
'Brachet noir et feu ;1',
'Brachet de Styrie ? poil dur ;1',
'Brachet polonais ;1',
'Brachet tyrolien ;1',
'Braque allemand ? poil court ;1',
'Braque d Auvergne ;1',
'Braque de Burgos ;1',
'Braque de l Ariege ;1',
'Braque du Bourbonnais ;1',
'Braque du Dupuy race disparue;1',
'Braque fran?ais ;1',
'Braque de Weimar ;1',
'Braque de Weimar ? poil court ;1',
'Braque de Weimar ? poil long ;1',
'Braque hongrois ? poil court ;1',
'Braque hongrois ? poil dur ;1',
'Braque italien ;1',
'Braque portugais ;1',
'Braque Saint-Germain ;1',
'Braque slovaque ? poil dur ;1',
'Griffon vendeen ;1',
'Broholmer ;1',
'Bruno du Jura;1',
'Bruno du Jura type Saint-Huber;1',
'Buhund norvegien ;1',
'Bull Boxer;1',
'Bull Terrier ;1',
'Bulldog anglais ;1',
'Bulldog Americain;1',
'Bulldog australien;1',
'Bullmastiff;1',
'Cairn Terrier ;1',
'Caniche ;1',
'Caniche Royal;1',
'Carlin;1',
'Cavalier King Charles Spaniel;1',
'Cavoodle;1',
'Charnaigre, race disparue;1',
'Chiba ;1',
'Chien Afghan;1',
'Chien africain;1',
'Chien d arret allemand ? poil ;1',
'Chien d arret danois ancestral;1',
'Chien d arret frison ;1',
'Chien d arret italien ? poil d;1',
'Chien d arret portugais ;1',
'Chien d Artois ;1',
'Chien de Bali ;1',
'Chien de Canaan ;1',
'Chien chanteur ;1',
'Chien chinois ? crete ;1',
'Chien chinois de Chongqing ;1',
'Chien Corse Cursinu ;1',
'Chien de Castro Laboreiro ;1',
'Chien de cour italien ;1',
'Chien courant de Bosnie ? poil;1',
'Chien courant espagnol ;1',
'Chien courant d Estonie ;1',
'Chien courant finlandais ;1',
'Chien courant grec ;1',
'Chien courant de Halden ;1',
'Chien courant de Hamilton ;1',
'Chien courant de Hygen ;1',
'Chien courant d Istrie ? poil ;1',
'Chien courant italien ;1',
'Chien courant italien ? poil d;1',
'Chien courant italien ? poil r;1',
'Chien courant de montagne du M;1',
'Chien courant norvegien ;1',
'Chien courant polonais ;1',
'Chien courant de Posavatz ;1',
'Chien courant de Schiller ;1',
'Chien courant serbe ou chien c;1',
'Chien courant slovaque ;1',
'Chien courant du Smaland ;1',
'Chien courant suisse ;1',
'Chien courant bernois ;1',
'Chien courant du Jura ;1',
'Chien courant lucernois ;1',
'Chien courant schwytzois ;1',
'Chien courant de Transylvanie ;1',
'Chien courant tricolore serbe ;1',
'Chien courant de Virelade, rac;1',
'Chien de ferme dano-suedois ;1',
'Chien d eau americain ;1',
'Chien d eau espagnol ;1',
'Chien d eau frison ;1',
'Chien d eau irlandais ;1',
'Chien d eau portugais;1',
'Chien d eau romagnol;1',
'Chien d elan norvegien gris;1',
'Chien d elan norvegien noir;1',
'Chien d elan suedois;1',
'Chien Fila de Saint Miguel;1',
'Chien finnois de Laponie;1',
'Chien de garenne des Canaries;1',
'Chien de Taimyr;1',
'Chien du Groenland;1',
'Chien leopard catahoula;1',
'Chien-loup de Saarloos;1',
'Chien-loup tchecoslovaque;1',
'Chien à loutre;1',
'Chien de montagne portugais;1',
'Chien de montagne des Pyrenees;1',
'Chien norvegien de macareux;1',
'Chien nu mexicain;1',
'Chien nu du Perou;1',
'Chien d ours de Carelie;1',
'Chien d oysel allemand;1',
'Chien paria;1',
'Chien de perdrix de Drente;1',
'Chien de recherche au sang de ;1',
'Chien de recherche au sang du ;1',
'Chien de Saint-Hubert ;1',
'Chien suedois de Laponie;1',
'Chien de Taiwan;1',
'Chien de Terre-Neuve;1',
'Chien thailandais ? crete dors;1',
'Chihuahua;1',
'Chinook;1',
'Chow-Chow;1',
'Cimarron uruguayen;1',
'Cirneco de l etna;1',
'Clumber Spaniel;1',
'Cockapoo;1',
'Cocker Spaniel americain;1',
'Cocker Spaniel anglais;1',
'Colley;1',
'Colley à poil long;1',
'Colley à poil court;1',
'Colley barbu;1',
'Chien noir et feu pour la chas;1',
'Coton de Tulear;1',
'Cursinu;1',
'Dalmatien;1',
'Dandie Dinmont Terrier;1',
'Deerhound;1',
'Dingo Americain;1',
'Dingo;1',
'Dogue du Tibet;1',
'Dobermann;1',
'Dogue allemand;1',
'Dogue argentin;1',
'Dogue de Bordeaux;1',
'Dogue des Canaries;1',
'Dogue de Majorque;1',
'English Coonhound;1',
'English Springer Spaniel;1',
'epagneul bleu de Picardie;1',
'epagneul breton;1',
'epagneul français;1',
'epagneul japonais;1',
'epagneul de Munster;1',
'Grand Munsterlander;1',
'Petit Munsterlander;1',
'epagneul nain continental;1',
'epagneul nain continental papi;1',
'epagneul nain continental phal;1',
'epagneul picard;1',
'epagneul de Pont-Audemer;1',
'epagneul de Saint-Usuge;1',
'epagneul tibetain;1',
'Esquimau americain;1',
'Esquimau canadien;1',
'Estonian Hound;1',
'Eurasier;1',
'Field Spaniel;1',
'Fila Brasileiro;1',
'Foxhound anglais;1',
'Foxhound americain;1',
'Fox Terrier;1',
'Fox-terrier à poil lisse;1',
'Fox-terrier à poil dur;1',
'Miniature Fox Terrier;1',
'Français blanc et noir;1',
'Français blanc et orange;1',
'Français tricolore;1',
'Gascon saintongeois;1',
'Goldendoodle;1',
'Golden Retriever;1',
'Goldador;1',
'Grand anglo-français blanc et ;1',
'Grand anglo-français tricolore;1',
'Grand basset griffon vendeen;1',
'Grand bleu de Gascogne;1',
'Grand bouvier suisse;1',
'Grand griffon vendeen;1',
'Griffon belge;1',
'Griffon bleu de Gascogne;1',
'Griffon boulet ? poil laineux;1',
'Griffon de Bresse;1',
'Griffon bruxellois;1',
'Griffon d arret à poil dur Kor;1',
'Griffon fauve de Bretagne;1',
'Griffon nivernais;1',
'Griffon d arret tcheque;1',
'Harrier;1',
'Hovawart;1',
'Huntaway;1',
'Husky de Sakhaline;1',
'Husky siberien;1',
'Irish wolfhound;1',
'Jack Russell Terrier;1',
'Jindo coreen;1',
'Jug;1',
'Kai;1',
'Kangal Dog;1',
'Keeshond;1',
'Kelpie australien;1',
'Kerry beagle;1',
'King Charles Spaniel;1',
'King Shepherd;1',
'Kishu;1',
'Komondor;1',
'Kooikerhondje;1',
'Koolie;1',
'Kromfohrlander;1',
'Kuchi dog;1',
'Kuvasz;1',
'Kyi Leo;1',
'Labernois;1',
'Labrabull;1',
'Labradinger;1',
'Labradoodle;1',
'Labrador;1',
'Labrastaff;1',
'Laika de Iakoutie;1',
'Laika de Siberie occidentale;1',
'Laika de Siberie orientale;1',
'Laika russo-europeen;1',
'Lakeland Terrier;1',
'Lancashire Heeler;1',
'Landseer;1',
'Leonberg;1',
'Levesque;1',
'Levrette italienne;1',
'Levrier afghan;1',
'Levrier arabe;1',
'Levrier australien;1',
'Levrier azawakh;1',
'Levrier Bakhmull;1',
'Levrier des Baleares;1',
'Levrier des Canaries;1',
'Levrier Caravan hound;1',
'Levrier Chortaj;1',
'Levrier ecossais;1',
'Levrier espagnol;1',
'Levrier grec;1',
'Levrier anglais;1',
'Levrier hongrois;1',
'Levrier irlandais;1',
'Levrier persan;1',
'Levrier de Pharaon;1',
'Levrier polonais;1',
'Levrier portugais;1',
'Levrier Rampur;1',
'Levrier russe;1',
'Levrier Taigan;1',
'Levrier de soie;1',
'Levrier whippet;1',
'Lhassa Apso;1',
'Lithuanian Hound;1',
'Longdog;1',
'Loulou de Pomeranie;1',
'Lurcher;1',
'Mackenzie River husky;1',
'Malamute d Alaska;1',
'malinois;1',
'Mal-shi;1',
'Manchester terrier;1',
'Mastiff;1',
'Mastiff d Anatolie;1',
'Maltipoo;1',
'Matin belge;1',
'Matin de l Alentejo;1',
'Matin des Pyrenees;1',
'Matin espagnol;1',
'Matin napolitain;1',
'Matin transmontano;1',
'Mountain Cur;1',
'Mudi;1',
'Norfolk Terrier ;1',
'Norwich Terrier ;1',
'Old English Bulldog;1',
'Papillon;1',
'Patterdale Terrier;1',
'Pekinois ;1',
'Perro fino Colombiano;1',
'Perro sin pelo del Peru;1',
'Petit basset griffon vendeen;1',
'Petit bleu de Gascogne;1',
'Petit brabançon;1',
'Petit chien courant suisse;1',
'Petit chien courant bernois;1',
'Petit chien courant lucernois;1',
'Petit chien courant schwytzois;1',
'Petit chien hollandais de chas;1',
'Petit chien lion;1',
'Petit chien russe;1',
'Petit levrier italien;1',
'Phalene;1',
'Pinscher autrichien;1',
'Pinscher allemand;1',
'Pinscher nain;1',
'pit-bull;1',
'Plott Hound;1',
'Pointer;1',
'Poitevin;1',
'Porcelaine;1',
'Pudelpointer;1',
'Puggle;1',
'Puli ;1',
'Pumi;1',
'Ratonero Bodeguero Andaluz;1',
'Ratier de Prague;1',
'Redbone Coonhound;1',
'Retriever de la baie de Chesap;1',
'Retriever du Labrador;1',
'Retriever de la Nouvelle-ecoss;1',
'Retriever à poil boucle;1',
'Retriever à poil plat;1',
'Rhodesian Ridgeback;1',
'Rottweiler;1',
'Sabueso espagnol;1',
'Saint-bernard;1',
'Samoyede;1',
'Sapsali;1',
'Schapendoes neerlandais;1',
'Sheeoadoodle;1',
'Schillerstovare;1',
'Schipperke;1',
'Schnauzer;1',
'Schnauzer nain;1',
'Schnauzer moyen;1',
'Schnauzer geant;1',
'Schnoodle;1',
'Schweizer Laufhund;1',
'Sealyham Terrier;1',
'Segugio Maremmano;1',
'Traineau de Siberie de Seppala;1',
'Setter anglais;1',
'Setter Gordon;1',
'Setter irlandais rouge;1',
'Setter irlandais rouge et blan;1',
'Shar Pei;1',
'Shiba Inu;1',
'Shih-poo;1',
'Shih Tzu;1',
'Shikoku;1',
'Skye Terrier;1',
'Smous des Pays-Bas;1',
'Spitz allemand;1',
'Spitz Loup;1',
'Grand spitz;1',
'Spitz moyen;1',
'Petit spitz;1',
'Spitz nain;1',
'Spitz de Norrbotten;1',
'Spitz des Visigoths;1',
'Spitz finlandais;1',
'Spitz italien;1',
'Spitz japonais ;1',
'Sporting Lucas Terrier;1',
'Staffordshire Bull Terrier;1',
'staffie;1',
'Staffordshire Terrier americai;1',
'Stephens Cur;1',
'Sussex Spaniel ;1',
'Talbot race disparue;1',
'Tamaskan;1',
'Tchouvatch slovaque;1',
'Teckel;1',
'Teddy Roosevelt Terrier;1',
'Tenterfield Terrier;1',
'Terre-neuve;1',
'Terrier australien;1',
'Terrier australien ? poil soye;1',
'Terrier bresilien;1',
'Terrier anglais d agrement noi;1',
'Terrier de Boston ;1',
'Terrier de chasse allemand;1',
'Terrier du Reverend Russel ;1',
'Terrier ecossais;1',
'Terrier gallois ;1',
'Terrier Glen of Imaal;1',
'Terrier irlandais ;1',
'Terrier irlandais ? poil doux ;1',
'Terrier japonais ;1',
'Terrier Kerry Blue ;1',
'Terrier noir ;1',
'Terrier tcheque ;1',
'Terrier tibetain;1',
'Texas Heeler;1',
'Kyi apso tibetain;1',
'Tosa;1',
'Bouledogue jouet;1',
'Jouet fox terrier;1',
'Jouet Manchester terrier;1',
'Treeing Cur;1',
'Treeing Tennessee Brindle;1',
'Treeing Walker Coonhound;1',
'Welsh Corgi Cardigan;1',
'Welsh Corgi Pembroke;1',
'epagneul springer gallois;1',
'Terrier blanc des Highlands de;1',
'Yorkillon;1',
'Yorkipoo;1',
'Yorkshire Terrier;1',
'Zuchon Shichon;1',
'Abyssin;2',
'American Bobtail;2',
'American Curl;2',
'American Shorthair;2',
'American Wirehair;2',
'Balinais;2',
'Bengal;2',
'Birman;2',
'Bombay;2',
'British Shorthair;2',
'Burmese;2',
'Burmilla;2',
'Californian Spangled;2',
'Chartreux;2',
'Chausie;2',
'Cornish Rex;2',
'Cymric;2',
'Devon Rex;2',
'Donskoy;2',
'Egyptian Mau;2',
'European Shorthair;2',
'Exotic Shorthair;2',
'German Rex;2',
'Havana Brown;2',
'Highland Fold;2',
'Himalayen;2',
'Japanese Bobtail;2',
'Javanais;2',
'Khao Manee;2',
'Korat;2',
'Kurilian Bobtail;2',
'LaPerm;2',
'Maine Coon;2',
'Manx;2',
'Mau Egyptien;2',
'Munchkin;2',
'Nebelung;2',
'Norvégien;2',
'Ocicat;2',
'Ojos Azules;2',
'Oriental;2',
'Persan;2',
'Peterbald;2',
'Pixie-bob;2',
'Ragdoll;2',
'Rex de Selkirk;2',
'Sacré de Birmanie;2',
'Savannah;2',
'Scottish Fold;2',
'Scottish Straight;2',
'Selkirk Rex;2',
'Serval domestique;2',
'Seychellois;2',
'Siamois;2',
'Sibérien;2',
'Singapura;2',
'Snowshoe;2',
'Autre;1',
'Autres;2',

        ];
        foreach ($data as $row) {
            list($raceName, $typeId) = explode(';', $row);
            $type = $manager->getRepository(Type::class)->find($typeId);
        
            $race = new Race();
            $race->setRaceAnimal($raceName);
            $race->setType($type); 
            $manager->persist($race);
        }
        
        $manager->flush();
    }
}

